### ISSUE TITLE
Add wormholes to faction systems again

### ISSUE THREAD

**Issue by DarcyManoel** [EndlessSkyCommunity/-Omnis#46]
#30 was relevant to the old faction wormholes feature, it has since been removed. Unsure on bringing it back.

**Comment by DOD8495Gym** [comment]
I wish it was brought back, as I can no longer access Omnis at all from my existing save.

**Comment by TheGiraffe3** [comment]
I would say we should - seeing as how somebody who starts with Omnis is already "cheating" it doesn't matter if they can take shortcuts through the galaxy.

**Comment by Hecter94** [comment]
They're generally useful for testing. 

If I want to test changes to a Wanderer mission or a Hai mission, for example, being able to start in Omnis, grab an appropriate ship/outfit, and then wormhole directly to the space that I'm interested in testing is a lot more convenient than having to start in Rutilicus and blindly jump to the faction space I'm looking for.

**Comment by TheGiraffe3** [comment]
We could make the wormholes have a custom government that's hostile to all governments except "Escort".
That would stop NPCs from using shortcuts, but the player still could.
