### ISSUE TITLE
Mission skip menu

### ISSUE THREAD

**Issue by DarcyManoel** [EndlessSkyCommunity/-Omnis#47]
https://github.com/EndlessSkyCommunity/world-forge/issues/28 world forge had this suggestion first.

Since I've been sitting on this consideration for a long while, I may well have a record of it. Skipping missions should be made to work independently of each other, but chained skips should only display in order and not alongside each other (to avoid situations like having the Wanderer story done but not FW).

Skips
- Sheragi archaeology 1/2 (to `Rim Archaeology 6`)
- FW story 1/2 (to `FW Defend New Tibet`)
   - FW story 2/2 (recon) (from `FW Reconciliation 1`)
   - FW story 2/2 (check) (from `FWC Scouting 1`)
      - Wanderer story 1/2 (to `Wanderers Ap'arak 3`)
         - Wanderer story 2/2 (from `Wanderers: Pre-Colony`)
      - Sheragi archaeology 2/2 (from `Sheragi Archaeology: The Box 1`)
- Remnant story 1/2 (to `Remnant: Technology Available`)
   - Remnant story 2/2 (from `Remnant: Learn Sign 1`)

**Comment by TheGiraffe3** [comment]
> * Remnant story 1/2 (to `Remnant: Technology Available`)
>   
>   * Remnant story 2/2 (from `Remnant: Learn Sign 1`)

I'm not sure about 2/2, because there isn't really a good point to drop the player into the story that I can remember.
Was there a specific place you were thinking of?
