### ISSUE TITLE
Poor Plugin Support

### ISSUE THREAD

**Issue by mOctave** [EndlessSkyCommunity/-Omnis#68]
Omnis is great for vanilla, but it doesn't work very well with plugins. Specifically, there's two big improvements that could be made
- Documentation, in the form of a list of shipyards/outfitters and description, to show plugin authors where to put their ships and outfits. Probably also a guide on how to connect a custom system up with Omnis.
- New "plugin" sales that are empty by default but can be expanded by plugins.
Of course, you could go further and include some plugin content by default, but I think those two points are all that's necessary.
Also, am I going gradually insane, or did Omnis used to have separate plugin sales?

**Comment by TheGiraffe3** [comment]
> • New "plugin" sales that are empty by default

How do you mean? Adding an empty shipyard/outfitter called `plugin`?

> Also, am I going gradually insane, or did Omnis use to have separate plugin sales?

I'm not sure. I don't think so.

**Comment by mOctave** [comment]
> How do you mean? Adding an empty shipyard/outfitter called plugin?

More "human plugin" / "korath plugin" etc. Creating an empty plugin shipyard/outfitter to match each standard one.

**Comment by TheGiraffe3** [comment]
I guess my main problem with that would be players not being able to tell what outfits are vanilla and what outfits are not.

**Comment by TheGiraffe3** [comment]
> New plugin sales _that are empty_

[This](https://github.com/TheGiraffe3/-Omnis/actions/runs/11287395678/job/31393270913?pr=7) is what I get when I try. I'm not sure what I could add to those. Maybe the Caster/a developer outfit?

**Comment by DarcyManoel** [comment]
It would be useful for the main game to have a indication on outfits if they are plugin content that show where they come from. Maybe an issue to be opened in Endless Sky.

**Comment by TheGiraffe3** [comment]
I believe that's been discussed before. Zitchas didn't like the idea, because it breaks immersion.

It would be though.

**Comment by TheGiraffe3** [comment]
Alright, PR is up.

Have you got any ideas for the text on the wiki page?

**Comment by mOctave** [comment]
Maybe a new page for plugin compatibility? I think the things to mention would be:
1. Where to find the arena script (the Arena page is kind of vague)
2. A list of the different plugin sales that are supported
3. Any best practices (for example, I found out five minutes ago that plugins are supposed to define their own systems and arenas)

**Comment by TheGiraffe3** [comment]
I'll work on the others, but I don't know what the arena script is either, so it would be nice to get input from Darcy on that.

**Comment by DarcyManoel** [comment]
> I'll work on the others, but I don't know what the arena script is either, so it would be nice to get input from Darcy on that.

https://darcymanoel.github.io/Endless-Sky-Lists/

**Comment by TheGiraffe3** [comment]
Here's the wiki page. I believe that should be everything.
https://github.com/EndlessSkyCommunity/-Omnis/wiki/Plugin-Support
